version: '3.9'

services:
  backend:
    build: ./backend
    container_name: npi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app  # Mount the entire directory for SQLite database file
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./npi.db  # Set the environment variable

  frontend:
    build: ./frontend
    container_name: npi_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000

volumes:
  sqlite_data:  
